Uniformize error messages for missing service

diff --git a/admin/create-amqp-extension b/admin/create-amqp-extension
--- a/admin/create-amqp-extension
+++ b/admin/create-amqp-extension
@@ -28,7 +28,9 @@ REMOTE_SQL_FILE=/tmp/CreateExtensionAMQP.sql
 
 if ! $DOCKER_COMPOSE_CMD ps indexer | grep -qw 'Up'
 then
-  echo >&2 "$SCRIPT_NAME: cannot install: 'indexer' is not a running Docker Compose service"
+  echo >&2 "$SCRIPT_NAME: cannot install: " \
+           "the Docker Compose service 'indexer' is not up"
+  echo >&2 "Try '$DOCKER_COMPOSE_CMD up -d indexer' from '$MB_DOCKER_ROOT'"
   exit 69
 fi
 
@@ -43,7 +45,8 @@ fi
 
 if $DOCKER_COMPOSE_CMD exec db test -e "$REMOTE_SQL_FILE"
 then
-  echo >&2 "$SCRIPT_NAME: cannot install: file '$REMOTE_SQL_FILE' exists in 'db' Docker Compose service"
+  echo >&2 "$SCRIPT_NAME: cannot install: " \
+           "file '$REMOTE_SQL_FILE' exists in 'db' Docker Compose service"
   echo >&2 "Either $SCRIPT_NAME is already running or stopped before its time."
   echo >&2 "Remove this file if you are sure the script is not still running:"
   echo >&2 "    $DOCKER_COMPOSE_CMD exec db rm -fv $(printf %q "$REMOTE_SQL_FILE")"
diff --git a/admin/setup-amqp-triggers b/admin/setup-amqp-triggers
--- a/admin/setup-amqp-triggers
+++ b/admin/setup-amqp-triggers
@@ -30,7 +30,9 @@ case "$1" in
   clean     )
     if ! $DOCKER_COMPOSE_CMD ps musicbrainz | grep -qw 'Up'
     then
-      echo >&2 "$SCRIPT_NAME: cannot clean: 'musicbrainz' is not a running docker compose service"
+      echo >&2 "$SCRIPT_NAME: cannot clean: " \
+               "the Docker Compose service 'musicbrainz' is not up"
+      echo >&2 "Try '$DOCKER_COMPOSE_CMD up -d musicbrainz' from '$MB_DOCKER_ROOT'"
       exit 69
     fi
 
@@ -42,7 +44,9 @@ case "$1" in
   install   )
     if ! $DOCKER_COMPOSE_CMD ps indexer | grep -qw 'Up'
     then
-      echo >&2 "$SCRIPT_NAME: cannot install: 'indexer' is not a running docker compose service"
+      echo >&2 "$SCRIPT_NAME: cannot install: " \
+               "the Docker Compose service 'indexer' is not up"
+      echo >&2 "Try '$DOCKER_COMPOSE_CMD up -d indexer' from '$MB_DOCKER_ROOT'"
       exit 69
     fi
 
@@ -85,7 +89,9 @@ case "$1" in
   uninstall )
     if ! $DOCKER_COMPOSE_CMD ps musicbrainz | grep -qw 'Up'
     then
-      echo >&2 "$SCRIPT_NAME: cannot uninstall: 'musicbrainz' is not a running docker compose service"
+      echo >&2 "$SCRIPT_NAME: cannot uninstall: " \
+               "the Docker Compose service 'musicbrainz' is not up"
+      echo >&2 "Try '$DOCKER_COMPOSE_CMD up -d musicbrainz' from '$MB_DOCKER_ROOT'"
       exit 69
     fi
 
