Refactor admin helper scripts
* Factorize initialization code in the separate lib/common.inc.bash
* Uniformize errors (stderr redirect, message format, exit status)
* Uniformize help messages, success messages, coding style, naming
* Try to auto-detect when 'sudo' must be used with 'docker' and
  'docker-compose' commands, with DOCKER_CMD and DOCKER_COMPOSE_CMD

diff --git a/admin/setup-amqp-triggers b/admin/setup-amqp-triggers
--- a/admin/setup-amqp-triggers
+++ b/admin/setup-amqp-triggers
@@ -2,89 +2,98 @@
 
 set -e -u
 
+source "$(dirname "${BASH_SOURCE[0]}")/lib/common.inc.bash"
+
 HELP=$(cat <<EOH
-Usage: $0 <clean|install|uninstall>
+Usage: $SCRIPT_NAME <clean|install|uninstall>
 
 Commands:
-  clean       Remove temporary install scripts and uninstall scripts
-  install     Create database triggers and add uninstall scripts
-  uninstall   Drop database triggers and remove uninstall scripts
+  clean       Remove temporary install scripts and uninstall scripts.
+  install     Create database triggers and add uninstall scripts.
+  uninstall   Drop database triggers and remove uninstall scripts.
 EOH
 )
 
-if [ $# -ne 1 ]; then
-  echo "$0: wrong number of arguments"
-  echo "$HELP"
-  exit 1
+if [ $# -ne 1 ]
+then
+  echo >&2 "$SCRIPT_NAME: wrong number of arguments"
+  echo >&2 "$HELP"
+  exit 64
 fi
 
-MB_DOCKER_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd)
 LOCAL_TRIGGERS_DIR="$(dirname "${BASH_SOURCE[0]}")/.setup-amqp-triggers-sql"
 REMOTE_TRIGGERS_DIR=/tmp/indexer-sql
 
-cd "$MB_DOCKER_ROOT"
-
 case "$1" in
   clean     )
-    if ! docker-compose ps musicbrainz | grep -qw 'Up'; then
-      echo "$0: cannot clean: 'musicbrainz' is not a running docker-compose service"
-      exit 1
+    if ! $DOCKER_COMPOSE_CMD ps musicbrainz | grep -qw 'Up'
+    then
+      echo >&2 "$SCRIPT_NAME: cannot clean: 'musicbrainz' is not a running docker compose service"
+      exit 69
     fi
 
     echo "Cleaning indexer triggers install/uninstall scripts up ..."
 
-    docker-compose exec musicbrainz rm -frv "$REMOTE_TRIGGERS_DIR"
+    $DOCKER_COMPOSE_CMD exec musicbrainz rm -frv "$REMOTE_TRIGGERS_DIR"
     rm -frv "$LOCAL_TRIGGERS_DIR"
     ;;
   install   )
-    if ! docker-compose ps indexer | grep -qw 'Up'; then
-      echo "$0: cannot install: 'indexer' is not a running docker-compose service"
-      exit 1
+    if ! $DOCKER_COMPOSE_CMD ps indexer | grep -qw 'Up'
+    then
+      echo >&2 "$SCRIPT_NAME: cannot install: 'indexer' is not a running docker compose service"
+      exit 69
     fi
 
-    if [ -e "$LOCAL_TRIGGERS_DIR" ]; then
-      echo "$0: cannot install: File '$LOCAL_TRIGGERS_DIR' exists"
-      exit 1
+    if [ -e "$LOCAL_TRIGGERS_DIR" ]
+    then
+      echo >&2 "$SCRIPT_NAME: cannot install: file '$LOCAL_TRIGGERS_DIR' exists"
+      exit 70
     fi
 
-    if docker-compose exec musicbrainz test -e "$REMOTE_TRIGGERS_DIR"; then
-      echo "$0: cannot install: File '$REMOTE_TRIGGERS_DIR' exists in 'musicbrainz' docker-compose service"
-      exit 1
+    if $DOCKER_COMPOSE_CMD exec musicbrainz test -e "$REMOTE_TRIGGERS_DIR"
+    then
+      echo >&2 "$SCRIPT_NAME: cannot install: file '$REMOTE_TRIGGERS_DIR' exists in 'musicbrainz' docker compose service"
+      exit 70
     fi
 
     echo "Installing indexer triggers ..."
 
-    docker-compose exec indexer python -m sir triggers
+    $DOCKER_COMPOSE_CMD exec indexer python -m sir triggers
 
-    indexer_container_id="$(docker-compose ps -q indexer)"
-    docker cp "$indexer_container_id":/code/sql "$LOCAL_TRIGGERS_DIR"
-    docker cp "$LOCAL_TRIGGERS_DIR" "$indexer_container_id":"$REMOTE_TRIGGERS_DIR"
+    indexer_container_id="$($DOCKER_COMPOSE_CMD ps -q indexer)"
+    $DOCKER_CMD cp "$indexer_container_id":/code/sql "$LOCAL_TRIGGERS_DIR"
+    $DOCKER_CMD cp "$LOCAL_TRIGGERS_DIR" "$indexer_container_id":"$REMOTE_TRIGGERS_DIR"
 
-    docker-compose exec musicbrainz /indexer-triggers.sh "$REMOTE_TRIGGERS_DIR" create
+    $DOCKER_COMPOSE_CMD exec musicbrainz /indexer-triggers.sh "$REMOTE_TRIGGERS_DIR" create
 
     rm -fr "$LOCAL_TRIGGERS_DIR"
     ;;
   uninstall )
-    if ! docker-compose ps musicbrainz | grep -qw 'Up'; then
-      echo "$0: Error: 'musicbrainz' is not a running docker-compose service"
-      exit 1
+    if ! $DOCKER_COMPOSE_CMD ps musicbrainz | grep -qw 'Up'
+    then
+      echo >&2 "$SCRIPT_NAME: cannot uninstall: 'musicbrainz' is not a running docker compose service"
+      exit 69
     fi
 
-    if docker-compose exec musicbrainz test ! -e "$REMOTE_TRIGGERS_DIR"; then
-      echo "$0: Error: File '$REMOTE_TRIGGERS_DIR' does not exist"
+    if $DOCKER_COMPOSE_CMD exec musicbrainz test ! -e "$REMOTE_TRIGGERS_DIR"
+    then
+      echo >&2 "$SCRIPT_NAME: cannot uninstall: file '$REMOTE_TRIGGERS_DIR' does not exist"
+      exit 70
     fi
 
     echo "Uninstalling indexer triggers ..."
 
-    docker-compose exec musicbrainz /indexer-triggers.sh "$REMOTE_TRIGGERS_DIR" drop
+    $DOCKER_COMPOSE_CMD exec musicbrainz /indexer-triggers.sh "$REMOTE_TRIGGERS_DIR" drop
 
-    docker-compose exec musicbrainz rm -fr "$REMOTE_TRIGGERS_DIR"
+    $DOCKER_COMPOSE_CMD exec musicbrainz rm -fr "$REMOTE_TRIGGERS_DIR"
     ;;
   *         )
-    echo "$0: unrecognized command '$1'"
-    echo "$HELP"
-    exit 1
+    echo >&2 "$SCRIPT_NAME: unrecognized command '$1'"
+    echo >&2 "$HELP"
+    exit 64
     ;;
 esac
 
 echo "Done."
+
+# vi: set et sts=2 sw=2 ts=2 :
